Try to fix #35
AppImage/type2-runtime pull request #36
Opened 2024-07-02 19:25 UTC by probonopd

Closes #35
Thanks @Bqleine

2024-07-02 19:38 UTC, probonopd commented
Why...

```
+ patch -p1
patching file lib/mount.c
patch: **** malformed patch at line 96:  		_exit(1);
```

2024-07-02 20:31 UTC, probonopd commented
Build [artifacts](https://github.com/AppImage/type2-runtime/actions/runs/9767294099/artifacts/1661245349) for testing.

2024-07-02 20:52 UTC, Bqleine commented on patches/libfuse/mount.c.diff
> ++		char binaryName[20];
Why twenty? It's at most thirteen characters including the null character, or twenty-one if you want to fit every integer.

2024-07-02 21:08 UTC, probonopd commented on patches/libfuse/mount.c.diff
> ++		char binaryName[20];
Agree. 13 it is.

2024-07-02 22:01 UTC, probonopd commented
Actually... won't

https://github.com/AppImage/type2-runtime/pull/32/files

fix this once it finally gets reviewed and merged?

2024-07-03 18:29 UTC, TheAssassin requested changes
Had a first glance. Please revisit, I'll have another look afterwards.

2024-07-03 18:29 UTC, TheAssassin commented on patches/libfuse/mount.c.diff
> ++		if (prog && access(prog, X_OK) == 0)
```suggestion
+		if (prog != NULL && access(prog, X_OK) == 0)
```

2024-07-03 18:37 UTC, probonopd commented on patches/libfuse/mount.c.diff
> ++		sprintf(binaryName, "fusermount%d", i);
`fusermount `... `fusermount99 `is what I had in mind

2024-07-03 19:41 UTC, probonopd commented on patches/libfuse/mount.c.diff
> ++		sprintf(binaryName, "fusermount%d", i);
Not sure what you mean with the further check - in which case would this even be needed?

2024-07-03 21:04 UTC, TheAssassin commented on patches/libfuse/mount.c.diff
> ++		sprintf(binaryName, "fusermount%d", i);
If `i` overflows for whatever reason (might be future changes), `snprintf` will not render additional digits but it'd be unexpected to run into the limit anyway. It's good practice to check the return value. See, e.g., https://stackoverflow.com/questions/54084570/how-to-detect-snprintf-errors.

2024-07-03 22:28 UTC, Bqleine commented
The more I look into this, the more it seems like a bad idea.

Firstly, @TheAssassin noticed the security issues in your patch and told you, but you merged the patch without more discussion. https://github.com/AppImage/type2-runtime/pull/11#issuecomment-1616169180

Then in the patch you wrote that « For security reasons, we do not search the binary on the $PATH; », but now we are doing it in #32?

I don't understand everything but we should seriously reconsider the security implications of doing such a patch. And ask libfuse's developers' opinion, as they either have a good reason of not doing it or could merge it directly upstream and give it a proper review for security issues.

Because putting buffer overflows in someone else's code is not ok.

2024-07-03 22:32 UTC, TheAssassin commented
I wish I had more time to work on AppImage and all of my other projects because I know I could handle most of this better, however that's likely not going to change soon. This is a tiny project team wise but has a large impact on users and developers, which is perfectly illustrated by https://xkcd.com/2347/ (change Nebraska to Germany).

2024-11-24 18:12 UTC, closed without merging