Add -Wall -Werror
AppImage/type2-runtime pull request #43
Opened 2024-07-13 15:07 UTC by probonopd

Closes #42

2024-07-13 16:28 UTC, probonopd commented
I did a smoke test of this runtime and it seems to work for me.

2024-07-14 13:33 UTC, TheAssassin requested changes

2024-07-14 13:33 UTC, TheAssassin commented on src/runtime/runtime.c
> +        fprintf(stderr, "Read of ELF header from %s failed: %s\n", fname, strerror(errno));
What's the motivation behind this change?

2024-07-14 13:33 UTC, TheAssassin commented on src/runtime/runtime.c
> +    sqfs_ll_ops.forget = (void (*)(struct fuse_req *, fuse_ino_t, uint64_t))sqfs_ll_op_forget;
Since all the other functions match the expected signature, I'd rather adapt the function signature of `sqfs_ll_op_forget`.

2024-07-14 13:33 UTC, TheAssassin commented on src/runtime/runtime.c
> +            for (size_t bytes_read; (bytes_read = fread(buf, sizeof(char), sizeof(buf), f)) > 0; ) {
The variable should be mutated in the third part of a `for` condition, not in the second. The check should be in the second.

2024-07-14 16:46 UTC, probonopd commented on src/runtime/runtime.c
> +        fprintf(stderr, "Read of ELF header from %s failed: %s\n", fname, strerror(errno));
Generally I try to keep one statement in one line unless it doesn't fit. Much more readable imho.

2024-07-14 16:51 UTC, probonopd commented on src/runtime/runtime.c
> +    sqfs_ll_ops.forget = (void (*)(struct fuse_req *, fuse_ino_t, uint64_t))sqfs_ll_op_forget;
Since the function is not defined in this file and I don't want to patch more than one file if not absolutely necessary, I'd suggest we keep this if it works.

2024-07-14 16:59 UTC, probonopd commented on src/runtime/runtime.c
> +            for (size_t bytes_read; (bytes_read = fread(buf, sizeof(char), sizeof(buf), f)) > 0; ) {
Can you please suggest a solution as I am not sure how I am supposed to change it and why.

2024-07-14 18:37 UTC, TheAssassin commented on src/runtime/runtime.c
> +        fprintf(stderr, "Read of ELF header from %s failed: %s\n", fname, strerror(errno));
While that is true, the change is unrelated to the respective commit. Please try to commit these changes separately to create atomic commits.

2024-07-25 15:47 UTC, Korne127 commented on src/runtime/runtime.c
> +            for (size_t bytes_read; (bytes_read = fread(buf, sizeof(char), sizeof(buf), f)) > 0; ) {
I think a solution would be to use a while loop instead:
```c
size_t bytes_read;
while ((bytes_read = fread(buf, sizeof(char), sizeof(buf), f)) > 0) {
    …
}
```

2024-07-27 02:38 UTC, probonopd commented on src/runtime/runtime.c
> +        fprintf(stderr, "Read of ELF header from %s failed: %s\n", fname, strerror(errno));
Maybe in the future, but I don't have the nerve to do git acrobatics to extract these changes after the fact just so that the git history separates them out.

2024-07-27 02:40 UTC, probonopd commented on src/runtime/runtime.c
> +            for (size_t bytes_read; (bytes_read = fread(buf, sizeof(char), sizeof(buf), f)) > 0; ) {
Thanks @Korne127. Am I correct in assuming that functionally, both are equivalent, and the only difference is whether the the variable `bytes_read ` is declared and initialized inside vs. outside the loop, so this is practically a matter of preference?

2024-07-27 02:42 UTC, probonopd commented
@TheAssassin if you have no objections, I'd like to merge this now.

2024-07-27 02:59 UTC, Korne127 commented on src/runtime/runtime.c
> +            for (size_t bytes_read; (bytes_read = fread(buf, sizeof(char), sizeof(buf), f)) > 0; ) {
Yep; these are equivalent; it's just preference / convention

2024-07-27 09:17 UTC, TheAssassin approved these changes

2024-07-27 10:44 UTC, merged