Improve build setup
AppImage/type2-runtime pull request #45
Opened 2024-07-27 10:46 UTC by TheAssassin

Improves the build system to use isolated environments.

In comparison to the old setup, this one can be run just fine on any developer workstation, too, without mutating the system. Also, it separates the dependency installation from the actual build (which does not require root permissions). Furthermore, dependencies are cached between builds, which mainly is useful for local development builds (it cuts down build times from minutes to seconds).

2024-07-27 11:24 UTC, probonopd requested changes
Currently the build fails

2024-07-27 12:08 UTC, probonopd commented on BUILD.md
> +The resulting AppImages will end up in your current working directory.
Please add a section on how to work interactively in such an environment.

Also, note that Docker does not work e.g., on FreeBSD whereas chroot does (using the Linuxulator, one can chroot into a n Alpine userland). Hence it must be ensured that the "legacy" scripts still work.

2024-07-27 12:08 UTC, probonopd commented on Dockerfile
> +RUN wget https://github.com/libfuse/libfuse/releases/download/fuse-3.15.0/fuse-3.15.0.tar.xz && \
Do we need these things as part of the Dockerfile?
I would prefer to have this in a shell script that can run either in chroot or in Docker, and maintain such things only in one place.

2024-07-27 12:08 UTC, probonopd commented on build-in-container.sh
Can we combine this with the "legacy" script, using if clauses? So that we don't have to maintain essentially the same stuff in 2 places.

2024-07-27 12:08 UTC, probonopd commented on src/runtime/runtime.c
Isn't this a separate change that should be its own PR?

2024-07-27 12:09 UTC, TheAssassin commented on BUILD.md
> +The resulting AppImages will end up in your current working directory.
We can add a script that just runs the container. That can be reused in the build script.

2024-07-27 12:10 UTC, TheAssassin commented on BUILD.md
> +The resulting AppImages will end up in your current working directory.
> Also, note that Docker does not work e.g., on FreeBSD whereas chroot does (using the Linuxulator, one can chroot into a n Alpine userland). Hence it must be ensured that the "legacy" scripts still work.

I kept the scripts in a separate directory. Please don't hesitate to test it yourself. To me, FreeBSD is not a relevant build environment, but as long as I don't have to maintain it, I don't mind it.

What about other container environments like podman, by the way?

2024-07-27 12:10 UTC, probonopd commented on BUILD.md
> +The resulting AppImages will end up in your current working directory.
And describe how to work interactively in there. Many people don't know that/how this is possible using Docker.

2024-07-27 12:10 UTC, TheAssassin commented on build-in-container.sh
The build-in-container script is supposed to be run from the chroot stuff.

2024-07-27 12:11 UTC, TheAssassin commented on src/runtime/runtime.c
Well, that's a lot more work. I don't see a point in it.

2024-07-27 12:26 UTC, probonopd commented on src/runtime/runtime.c
OK, let's be pragmatic then. Build still fails btw

2024-07-27 13:12 UTC, TheAssassin commented on Dockerfile
> +RUN wget https://github.com/libfuse/libfuse/releases/download/fuse-3.15.0/fuse-3.15.0.tar.xz && \
Please see the description of the PR. It's obviously a massive speed-up.

We can extract it into a shell script which you can use in your chroot setup, too.

2024-07-27 13:14 UTC, TheAssassin commented on BUILD.md
> +The resulting AppImages will end up in your current working directory.
> Many people don't know that/how this is possible using Docker.

I'd say everyone willing to contribute knows enough about Docker to work with it especially with the elaborate instructions provided in the READMEs.

The opposite is true for this `chroot` setup that, again, breaks stuff if you're not extremely careful.

> And describe how to work interactively in there. 

It's a shell. I expect people to work with a shell.

2024-07-27 13:17 UTC, probonopd commented on Dockerfile
> +RUN wget https://github.com/libfuse/libfuse/releases/download/fuse-3.15.0/fuse-3.15.0.tar.xz && \
Yes, let's do that then. Don't forget to update the chroot setup to use it.

2024-07-27 13:17 UTC, probonopd commented on BUILD.md
> +The resulting AppImages will end up in your current working directory.
Let's just assume people have never used Docker. Our audience is desktop oriented whereas Docker is mainly known in server circles.

2024-07-27 13:18 UTC, TheAssassin commented on Dockerfile
> +RUN wget https://github.com/libfuse/libfuse/releases/download/fuse-3.15.0/fuse-3.15.0.tar.xz && \
I asked you to do the detail work above already. I don't want to have to run a FreeBSD for every tiny change that is relevant basically just for the few times you run a BSD.

2024-07-27 13:39 UTC, probonopd commented on Dockerfile
> +RUN wget https://github.com/libfuse/libfuse/releases/download/fuse-3.15.0/fuse-3.15.0.tar.xz && \
I don't have a BSD handy at the moment. The chroot stuff of course also works on a Linux host.

2024-07-28 12:33 UTC, TheAssassin commented
Build fixed. We should merge this now. I'll fix the "old" legacy chroot build setup in an upcoming PR then.

2024-07-28 13:33 UTC, TheAssassin commented
I even fixed the chroot workflow. Please review.

2024-07-28 16:07 UTC, probonopd commented
Thanks @TheAssassin, but we also need to (occasionally) run it to see if it works. Added a step for it.

2024-07-28 16:20 UTC, probonopd commented
@TheAssassin, it tries to download `alpine-minirootfs-3.17.2-i686.tar.gz` but it is called ``x86.tar.gz`. I think you changed something regarding `$ARCHITECTURE`...

2024-07-28 16:29 UTC, probonopd commented on .github/workflows/build.yaml
> +        - appimage_arch: i686
@TheAssassin, it tries to download `alpine-minirootfs-3.17.2-i686.tar.gz` but it is called `alpine-minirootfs-3.17.2-x86.tar.gz`. I think you changed something regarding `$ARCHITECTURE`...

2024-07-28 16:30 UTC, probonopd commented on legacy/build.sh
> +apk add alpine-sdk util-linux strace file autoconf automake libtool xz bash
Can we do posix sh, so that bash is not needed?

2024-07-28 16:30 UTC, probonopd commented on legacy/chroot_build.sh
> +#! /bin/bash
Can we do posix sh, so that bash is not needed?

2024-07-28 16:32 UTC, probonopd commented on legacy/chroot_build.sh
> -#!/bin/sh
Let's not call this directory "legacy", but "chroot" or something like that. We should not suggest that we have something outdated in this repository.

2024-07-28 16:32 UTC, probonopd requested changes
Hi @TheAssassin, great progress. Please see inline comments.

2024-07-28 21:09 UTC, TheAssassin commented on legacy/build.sh
> +apk add alpine-sdk util-linux strace file autoconf automake libtool xz bash
No. Generic shells do not support any useful features regarding error handling.

2024-07-28 21:09 UTC, TheAssassin commented on legacy/chroot_build.sh
> +#! /bin/bash
See https://github.com/AppImage/type2-runtime/pull/45#discussion_r1694333477. It makes no sense.

2024-07-28 21:09 UTC, TheAssassin commented on legacy/chroot_build.sh
> -#!/bin/sh
In my opinion, this entire build system is obsolete. But feel free to modify the branch.

2024-07-28 21:10 UTC, TheAssassin commented on .github/workflows/build.yaml
> +        - appimage_arch: i686
Your variable naming never made a lot of sense. The variables I define here are not supposed(!) to work with the chroot setup. Since you want to run these builds along with the other ones, please fix this yourself.

2024-07-28 21:12 UTC, TheAssassin commented on .github/workflows/build.yaml
> +        - appimage_arch: aarch64
You should rename the variable to, e.g., `architecture`, as this corresponds to the env var's name.

The scripts autodetect the build environment's target CPU architecture already. Just use `x86` instead of `i686`.

2024-07-31 19:56 UTC, probonopd approved these changes

2024-07-31 19:56 UTC, probonopd commented on .github/workflows/build.yaml
> +        - appimage_arch: i686
Added a fix that (hopefully) will address that.

2024-07-31 19:56 UTC, probonopd commented on legacy/chroot_build.sh
> +#! /bin/bash
Added a fix that (hopefully) will address that.

2024-07-31 19:56 UTC, probonopd commented on .github/workflows/build.yaml
> +        - appimage_arch: aarch64
Added a fix that resolves this.

2024-07-31 19:57 UTC, probonopd commented on legacy/chroot_build.sh
> -#!/bin/sh
Done.

2024-07-31 23:18 UTC, merged

2024-07-31 23:19 UTC, TheAssassin commented
By the way, the chroot-based setup now also uses temporary directories for everything, making it a suitable build and test environment. The chroot root directories used to be somewhat ephemeral already, but this PR certainly improved the isolation quite a bit.