Optimize for size
AppImage/type2-runtime pull request #7
Opened 2023-06-20 17:08 UTC by probonopd

https://github.com/AppImage/AppImageKit/issues/877#issuecomment-1597855286

2023-06-20 17:16 UTC, probonopd commented
Why do we get `/usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: cannot find -lzstd: No such file or directory` for ARM?

2023-06-25 10:21 UTC, probonopd commented
It says

```
  (4/7) Installing zlib-dev (1.2.13-r1)
  (5/7) Installing zlib-static (1.2.13-r1)
  (6/7) Installing zstd (1.5.5-r4)
  (7/7) Installing zstd-dev (1.5.5-r4)
```

why does it produce that error then?

2023-06-25 10:34 UTC, probonopd commented
Blocked by https://github.com/AppImage/type2-runtime/pull/8

2023-06-26 00:57 UTC, TheAssassin requested changes

2023-06-26 00:57 UTC, TheAssassin commented on build.sh
> +export CFLAGS="-ffunction-sections -fdata-sections -Os"
I think `-Os` is unnecessary, the rest is fine.

In my opinion, in the long run, we need to be able to debug runtimes properly, so we might upload debug symbols for it in this repository, too. Any kind of optimization that is not coordinated with that goal should be postponed.

2023-07-01 18:51 UTC, probonopd commented on build.sh
> +export CFLAGS="-ffunction-sections -fdata-sections -Os"
Using this for now; feel free to remove the `-Os` in case you think it is harmful. ("Doppelt gemoppelt hält besser")

2023-07-01 22:32 UTC, TheAssassin commented on build.sh
> +export CFLAGS="-ffunction-sections -fdata-sections -Os"
I have no objections right now. We can always remove it if we find problems. I even consulted the GCC manual, and it just mentions it will exclude some optimizations that could potentially inflate the binary size. That means that the code won't run faster in some edge cases, but won't introduce any breaking changes. This is completely acceptable to me.

2023-07-01 22:33 UTC, TheAssassin approved these changes

2023-07-01 22:33 UTC, merged